export default county = [
  'Norrbotten',
  'Västerbotten',
  'Jämtland',
  'Västernorrland',
  'Gävleborg',
  'Dalarna',
  'Västmanland',
  'Örebro',
  'Värmland',
  'Västra Götaland',
  'Halland',
  'Skåne',
  'Blekinge',
  'Gotland',
  'Kalmar',
  'Kronoberg',
  'Jönköping',
  'Östergötland',
  'Södermanland',
  'Uppsala',
  'Stockholm'
]
